CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_id    BIGINT                                  NOT NULL,
    to_id      BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

ALTER TABLE likes
    ADD CONSTRAINT uk_likes_from_to UNIQUE (from_id, to_id);

CREATE INDEX idx_likes_from_created
    ON likes (from_id, created_at DESC, id DESC);