CREATE TABLE unlike
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_id    BIGINT                                  NOT NULL,
    to_id      BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_unlike PRIMARY KEY (id)
);

ALTER TABLE unlike
    ADD CONSTRAINT uk_unlike_from_to UNIQUE (from_id, to_id);

CREATE INDEX idx_unlike_from_created
    ON unlike (from_id, created_at DESC, id DESC);