CREATE TABLE review
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_id    BIGINT                                  NOT NULL,
    to_id      BIGINT                                  NOT NULL,
    nickname   VARCHAR(15)                             NOT NULL,
    content    VARCHAR(500)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

CREATE INDEX idx_review_to_created
    ON review (to_id, created_at DESC, id DESC)
    WHERE deleted_at IS NULL;