CREATE TABLE private_image_grant
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_id    BIGINT                                  NOT NULL,
    to_id      BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_private_image_grant PRIMARY KEY (id)
);

ALTER TABLE private_image_grant
    ADD CONSTRAINT uk_private_image_grant_from_to UNIQUE (from_id, to_id);

CREATE INDEX idx_private_image_grant_from_created
    ON private_image_grant (from_id, created_at DESC, id DESC);