CREATE TABLE block
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_id    BIGINT                                  NOT NULL,
    to_id      BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_block PRIMARY KEY (id)
);

ALTER TABLE block
    ADD CONSTRAINT uk_block_from_to UNIQUE (from_id, to_id);

CREATE INDEX idx_block_from_created
    ON block (from_id, created_at DESC, id DESC);