CREATE TABLE report
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_id       BIGINT                                  NOT NULL,
    from_phone    VARCHAR(20)                             NOT NULL,
    from_nickname VARCHAR(15)                             NOT NULL,
    to_id         BIGINT                                  NOT NULL,
    to_phone      VARCHAR(20)                             NOT NULL,
    to_nickname   VARCHAR(15)                             NOT NULL,
    type          VARCHAR(10)                             NOT NULL,
    reason        VARCHAR(500)                            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_report PRIMARY KEY (id)
);