CREATE TABLE report_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_id  BIGINT                                  NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    url        VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_report_image PRIMARY KEY (id)
);

ALTER TABLE report_image
    ADD CONSTRAINT uc_report_image_key UNIQUE (key);

ALTER TABLE report_image
    ADD CONSTRAINT uc_report_image_url UNIQUE (url);