CREATE TABLE ban
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       VARCHAR(36)                             NOT NULL,
    type       VARCHAR(10)                             NOT NULL,
    target     VARCHAR(50)                             NOT NULL,
    reason     VARCHAR(100)                            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    expired_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_ban PRIMARY KEY (id)
);

ALTER TABLE ban
    ADD CONSTRAINT uc_ban_uuid UNIQUE (uuid);