CREATE TABLE ban_history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ban_id     BIGINT                                  NOT NULL,
    type       VARCHAR(10)                             NOT NULL,
    target     VARCHAR(50)                             NOT NULL,
    phone      VARCHAR(20),
    device_id  VARCHAR(36),
    nickname   VARCHAR(15),
    reason     VARCHAR(100)                            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    expired_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_ban_history PRIMARY KEY (id)
);