CREATE TABLE verification_code
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone      VARCHAR(20)                             NOT NULL,
    device_id  VARCHAR(36)                             NOT NULL,
    ip         VARCHAR(50)                             NOT NULL,
    code       VARCHAR(10)                             NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_verification_code PRIMARY KEY (id)
);