CREATE TABLE push
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_push PRIMARY KEY (id)
);

ALTER TABLE push
    ADD CONSTRAINT uc_push_token UNIQUE (token);