CREATE TABLE chat_message_reaction
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_message_id BIGINT                                  NOT NULL,
    member_id       BIGINT                                  NOT NULL,
    type            VARCHAR(20)                             NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_chat_message_reaction PRIMARY KEY (id)
);

ALTER TABLE chat_message_reaction
    ADD CONSTRAINT uk_chat_message_reaction_chat_message_id_member_id UNIQUE (chat_message_id, member_id);