CREATE TABLE member
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone       VARCHAR(20)                             NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    device_id   VARCHAR(36)                             NOT NULL,
    profile_url VARCHAR(255),
    nickname    VARCHAR(15)                             NOT NULL,
    gender      VARCHAR(10)                             NOT NULL,
    region      VARCHAR(20)                             NOT NULL,
    birth_year  INTEGER                                 NOT NULL,
    comment     VARCHAR(50)                             NOT NULL,
    bio         VARCHAR(500)                            NOT NULL,
    is_chat     BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    deleted_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uc_member_nickname
    ON member (nickname)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uc_member_phone
    ON member (phone)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_member_updated_id
    ON member (updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;