CREATE TABLE member_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    type       VARCHAR(10)                             NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    url        VARCHAR(255)                            NOT NULL,
    sort_order INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_member_image PRIMARY KEY (id)
);

ALTER TABLE member_image
    ADD CONSTRAINT uc_member_image_key UNIQUE (key);

ALTER TABLE member_image
    ADD CONSTRAINT uc_member_image_url UNIQUE (url);