CREATE TABLE chat_room
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member1_id                   BIGINT                                  NOT NULL,
    member2_id                   BIGINT                                  NOT NULL,
    member1_last_read_message_id BIGINT                                  NOT NULL,
    member2_last_read_message_id BIGINT                                  NOT NULL,
    last_message_preview         VARCHAR(100)                            NOT NULL,
    last_message_at              TIMESTAMP WITH TIME ZONE                NOT NULL,
    created_at                   TIMESTAMP WITH TIME ZONE                NOT NULL,
    deleted_at                   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_chat_room PRIMARY KEY (id)
);

ALTER TABLE chat_room
    ADD CONSTRAINT chk_member_order CHECK (member1_id < member2_id);

CREATE UNIQUE INDEX uc_chat_room_members
    ON chat_room (member1_id, member2_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_chat_room_member2_id
    ON chat_room (member2_id)
    WHERE deleted_at IS NULL;