CREATE TABLE chat_message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_room_id BIGINT                                  NOT NULL,
    sender_id    BIGINT                                  NOT NULL,
    type         VARCHAR(10)                             NOT NULL,
    content      TEXT                                    NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_chat_message PRIMARY KEY (id)
);

CREATE INDEX idx_chat_message_room_created
    ON chat_message (chat_room_id, created_at DESC, id DESC);