CREATE TABLE chat_message_media
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_message_id BIGINT                                  NOT NULL,
    type            VARCHAR(10)                             NOT NULL,
    url             VARCHAR(255)                            NOT NULL,
    key             VARCHAR(255)                            NOT NULL,
    thumbnail_url   VARCHAR(255),
    thumbnail_key   VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_chat_message_media PRIMARY KEY (id)
);