CREATE TABLE point
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    balance    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_point PRIMARY KEY (id)
);

ALTER TABLE point
    ADD CONSTRAINT uc_point_member UNIQUE (member_id);