CREATE TABLE point_history
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    point_id         BIGINT                                  NOT NULL,
    source           VARCHAR(20)                             NOT NULL,
    balance_snapshot BIGINT                                  NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_point_history PRIMARY KEY (id)
);

CREATE INDEX idx_point_history_point_created
    ON point_history (point_id, created_at DESC, id DESC);