spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gugutalk
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      password:
jwt:
  secret: a-string-secret-at-least-256-bits-long
  access-token-expire-seconds: 3600 # 1시간
  refresh-token-expire-seconds: 1209600 # 14일